import type { AgentRole, SwarmMessage } from "@/types";
import { Annotation } from "@langchain/langgraph";

/**
 * LangGraph state annotation for the multi-agent critique swarm.
 *
 * Each node reads from and writes to this shared state.
 * LangGraph handles state transitions and checkpointing.
 */
export const SwarmAnnotation = Annotation.Root({
  /** The user's original task description */
  task: Annotation<string>,

  /** Plan generated by the planner agent */
  plan: Annotation<string>({ reducer: (_, v) => v, default: () => "" }),

  /** Code generated by the coder agent */
  code: Annotation<string>({ reducer: (_, v) => v, default: () => "" }),

  /** Review from the reviewer agent */
  review: Annotation<string>({ reducer: (_, v) => v, default: () => "" }),

  /** Test results from the tester agent */
  testResults: Annotation<string>({ reducer: (_, v) => v, default: () => "" }),

  /** Inspiration references from the inspiration agent */
  inspiration: Annotation<string>({ reducer: (_, v) => v, default: () => "" }),

  /** Animation review from the animation critic agent */
  animationReview: Annotation<string>({ reducer: (_, v) => v, default: () => "" }),

  /** Accumulated messages from all agents */
  messages: Annotation<SwarmMessage[]>({
    reducer: (prev, next) => [...prev, ...next],
    default: () => [],
  }),

  /** Current iteration (for auto-iteration loop) */
  iteration: Annotation<number>({ reducer: (_, v) => v, default: () => 0 }),

  /** Max iterations before stopping */
  maxIterations: Annotation<number>({ reducer: (_, v) => v, default: () => 3 }),

  /** Current phase */
  status: Annotation<string>({
    reducer: (_, v) => v,
    default: () => "planning" as const,
  }),
});

export type SwarmState = typeof SwarmAnnotation.State;

/** System prompts for each agent role */
export const AGENT_PROMPTS: Record<AgentRole, string> = {
  planner: `You are a senior software architect. Given a task, produce a clear,
actionable implementation plan. Break it into numbered steps. Identify key files,
dependencies, and potential risks. Be specific and concise.`,

  coder: `You are an expert TypeScript/React developer. Given a plan, write clean,
production-ready code. Follow best practices: proper error handling, types, no
any types, meaningful names. Output complete, working code — not pseudocode.`,

  reviewer: `You are a thorough code reviewer. Examine the code for:
- Bugs and logic errors
- Security vulnerabilities (XSS, injection, etc.)
- Performance issues
- TypeScript type safety
- Missing error handling
Score 0-100. If score < 80, explain exactly what needs fixing.`,

  tester: `You are a QA engineer. Given code, write comprehensive test scenarios.
Identify edge cases, failure modes, and integration points. Determine if the code
is production-ready. If not, describe specific issues to fix.`,

  inspiration: `You are a creative UI/CSS inspiration agent, deeply familiar with
Jhey Tompkins' CodePen work and modern CSS techniques. Given a task, suggest:
- Creative CSS approaches (3D transforms, clip-path, scroll-driven animations)
- Relevant patterns from Jhey's demos (hover effects, playful interactions)
- Modern CSS features (container queries, :has(), color-mix(), oklch)
- Animation ideas that would elevate the UI
Be specific with code snippets. Focus on delight and polish.`,

  "animation-critic": `You are an Animation Critic specializing in web UI motion design.
Evaluate animations and transitions for:
1. Performance (GPU-accelerated properties only, no layout thrashing)
2. Accessibility (prefers-reduced-motion, no seizure-inducing patterns)
3. Creativity (advanced techniques, spring physics, meaningful motion)
4. Polish (consistent timing, staggered entrances, exit animations)
Score 0-100. Suggest improvements with Framer Motion or CSS examples.
Reference Jhey Tompkins patterns when applicable.`,
};
