import type { AgentRole, SwarmMessage } from "@/types";
import { Annotation } from "@langchain/langgraph";

/**
 * LangGraph state annotation for the multi-agent critique swarm.
 *
 * Each node reads from and writes to this shared state.
 * LangGraph handles state transitions and checkpointing.
 */
export const SwarmAnnotation = Annotation.Root({
  /** The user's original task description */
  task: Annotation<string>,

  /** Plan generated by the planner agent */
  plan: Annotation<string>({ reducer: (_, v) => v, default: () => "" }),

  /** Code generated by the coder agent */
  code: Annotation<string>({ reducer: (_, v) => v, default: () => "" }),

  /** Review from the reviewer agent */
  review: Annotation<string>({ reducer: (_, v) => v, default: () => "" }),

  /** Test results from the tester agent */
  testResults: Annotation<string>({ reducer: (_, v) => v, default: () => "" }),

  /** Accumulated messages from all agents */
  messages: Annotation<SwarmMessage[]>({
    reducer: (prev, next) => [...prev, ...next],
    default: () => [],
  }),

  /** Current iteration (for auto-iteration loop) */
  iteration: Annotation<number>({ reducer: (_, v) => v, default: () => 0 }),

  /** Max iterations before stopping */
  maxIterations: Annotation<number>({ reducer: (_, v) => v, default: () => 3 }),

  /** Current phase */
  status: Annotation<string>({
    reducer: (_, v) => v,
    default: () => "planning" as const,
  }),
});

export type SwarmState = typeof SwarmAnnotation.State;

/** System prompts for each agent role */
export const AGENT_PROMPTS: Record<AgentRole, string> = {
  planner: `You are a senior software architect. Given a task, produce a clear,
actionable implementation plan. Break it into numbered steps. Identify key files,
dependencies, and potential risks. Be specific and concise.`,

  coder: `You are an expert TypeScript/React developer. Given a plan, write clean,
production-ready code. Follow best practices: proper error handling, types, no
any types, meaningful names. Output complete, working code — not pseudocode.`,

  reviewer: `You are a thorough code reviewer. Examine the code for:
- Bugs and logic errors
- Security vulnerabilities (XSS, injection, etc.)
- Performance issues
- TypeScript type safety
- Missing error handling
Score 0-100. If score < 80, explain exactly what needs fixing.`,

  tester: `You are a QA engineer. Given code, write comprehensive test scenarios.
Identify edge cases, failure modes, and integration points. Determine if the code
is production-ready. If not, describe specific issues to fix.`,
};
